### ISSUE TITLE
Sharing the model for STYLEGAN-SSD

### ISSUE THREAD

**Issue by yaseryacoob** [cyq373/SSD-GAN#1]
A couple of requests, I am trying to see how much of an improvement is achieved by your paper:
1. Can you share the trained SSD-STYLEGAN model?
2. 2. Figure 7 in your paper is important because it is apples to apples comparison.  I am not sure it solved the high frequency problem. I would like to look more thoroughly at this. How can I use your C (the spectral classifier in your code on 2 images)?

thanks!

**Comment by cyq373** [comment]
Hi, thank you for your interest in our work.
The model weight of SSD-StyleGAN is [here](https://drive.google.com/file/d/1Hse5PjWR_SLhOY0XbrsORgsCUclrzCfT/view?usp=sharing).
You can use it by 
```
from training import misc # The raw code of StyleGAN

_, _, _, G = misc.load_pkl('SSD-StyleGAN.pkl')
```
