### ISSUE TITLE
A question about SNGAN baseline on STL-10

### ISSUE THREAD

**Issue by LittlelittleZ** [cyq373/SSD-GAN#3]
Hi, I noticed your novel paper SSD-GAN reported a STL-10 result of SNGAN achieved FID 39.56, which is lower than SNGAN-Paper's result, I'm interested in how to get a better generation result on STL-10, could you share the code or methods about this?
Hope my issue won't bother you, best wishes!

**Comment by cyq373** [comment]
Hi, please refer to this awesome [library](https://github.com/kwotsin/mimicry) to reproduce the SNGAN baseline, which is the basis of this project.

**Comment by LittlelittleZ** [comment]
Hi, thank you so much! I'll have a try. Best wishes!
